"""
HTML Report Generator — produces an interactive, self-contained HTML security report.

Features:
  - Single-file output with embedded CSS + JS (no external dependencies offline)
  - Chart.js charts (severity donut, protocol pie, traffic direction bar, top IPs/ports)
  - Sortable alert table
  - Collapsible investigation cards (<details>/<summary>)
  - Dark-mode support via prefers-color-scheme
  - Responsive layout
"""

from __future__ import annotations

import html
import logging
import time
from datetime import datetime
from pathlib import Path
from typing import Optional

from .models import Alert, ProcessProfile, Severity

logger = logging.getLogger("netwatch.html_report")

# ======================================================================
# Colour palette (hex)
# ======================================================================

_COLOURS = {
    Severity.LOW:      "#3498db",
    Severity.MEDIUM:   "#f1c40f",
    Severity.HIGH:     "#e74c3c",
    Severity.CRITICAL: "#9b59b6",
}


def _esc(text) -> str:
    """Escape text for safe HTML embedding."""
    return html.escape(str(text)) if text is not None else ""


class HTMLReportGenerator:
    """Generates a comprehensive NetWatch HTML report."""

    def __init__(self):
        from . import __version__
        self._version = __version__

    def generate(
        self,
        output_path: str,
        *,
        alerts: Optional[list[Alert]] = None,
        profiles: Optional[list[ProcessProfile]] = None,
        investigations: Optional[list] = None,
        dll_results: Optional[list] = None,
        feed_status: Optional[dict] = None,
        scan_duration: Optional[float] = None,
        connection_count: int = 0,
        network_stats: Optional[dict] = None,
        task_findings: Optional[list] = None,
        response_results: Optional[list] = None,
        network_map_path: Optional[str] = None,
    ) -> str:
        """Build and save an HTML report. Returns the output file path."""
        alerts = alerts or []
        profiles = profiles or []
        now = datetime.now()

        sev_counts = {s: 0 for s in Severity}
        for a in alerts:
            sev_counts[a.severity] += 1

        overall_risk = self._overall_risk(alerts)
        risk_color = _COLOURS.get(overall_risk, "#333")

        parts: list[str] = []
        parts.append(self._html_head(now))
        parts.append(self._cover_section(now, alerts, profiles, scan_duration, connection_count, overall_risk, risk_color))
        parts.append(self._executive_summary(sev_counts, alerts, profiles, scan_duration, connection_count))

        if network_stats:
            parts.append(self._network_stats_section(network_stats))

        if network_map_path:
            parts.append(self._network_map_section(network_map_path))

        if alerts:
            parts.append(self._alerts_section(alerts))

        if task_findings:
            parts.append(self._task_findings_section(task_findings))

        if response_results:
            parts.append(self._response_results_section(response_results))

        if profiles:
            parts.append(self._process_section(profiles))

        if investigations:
            parts.append(self._investigation_section(investigations))

        if dll_results:
            parts.append(self._dll_section(dll_results))

        if feed_status:
            parts.append(self._feed_section(feed_status))

        parts.append(self._recommended_actions(alerts, profiles, dll_results))

        # Charts data
        chart_data = self._build_chart_data(sev_counts, network_stats)
        parts.append(self._chart_scripts(chart_data))
        parts.append(self._html_footer())

        content = "\n".join(parts)

        out = Path(output_path)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(content, encoding="utf-8")
        logger.info("HTML report saved: %s", out)
        return str(out.resolve())

    # ==================================================================
    # HTML structure
    # ==================================================================

    def _html_head(self, now: datetime) -> str:
        return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>NetWatch Security Report — {now.strftime('%Y-%m-%d %H:%M')}</title>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.0/dist/chart.umd.min.js"></script>
{self._css()}
</head>
<body>
<div class="container">
"""

    @staticmethod
    def _html_footer() -> str:
        return """
</div>
<footer>
  <p>Generated by NetWatch &mdash; Network Traffic Anomaly Detector</p>
</footer>
</body>
</html>"""

    # ==================================================================
    # CSS
    # ==================================================================

    @staticmethod
    def _css() -> str:
        return """<style>
:root {
  --bg: #ffffff;
  --bg2: #f8f9fa;
  --text: #1e1e1e;
  --text-dim: #6c757d;
  --border: #dee2e6;
  --accent: #2ecc71;
  --card-bg: #ffffff;
  --card-shadow: 0 2px 8px rgba(0,0,0,0.08);
  --sev-low: #3498db;
  --sev-medium: #f1c40f;
  --sev-high: #e74c3c;
  --sev-critical: #9b59b6;
}
@media (prefers-color-scheme: dark) {
  :root {
    --bg: #1a1a2e;
    --bg2: #16213e;
    --text: #e0e0e0;
    --text-dim: #999;
    --border: #333;
    --card-bg: #1f2937;
    --card-shadow: 0 2px 8px rgba(0,0,0,0.3);
  }
}
* { margin: 0; padding: 0; box-sizing: border-box; }
body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  background: var(--bg);
  color: var(--text);
  line-height: 1.6;
}
.container { max-width: 1100px; margin: 0 auto; padding: 20px; }
footer { text-align: center; padding: 30px; color: var(--text-dim); font-size: 0.85em; }

/* Cover */
.cover { text-align: center; padding: 50px 20px 30px; }
.cover h1 { font-size: 2.8em; margin-bottom: 5px; }
.cover .subtitle { color: var(--text-dim); font-size: 1.1em; margin-bottom: 20px; }
.cover .accent-line { width: 100px; height: 4px; background: var(--accent); margin: 0 auto 25px; border-radius: 2px; }
.cover .meta { color: var(--text-dim); font-size: 0.95em; }
.risk-badge {
  display: inline-block; padding: 8px 28px; border-radius: 6px;
  color: #fff; font-weight: 700; font-size: 1.1em; margin-top: 20px;
  letter-spacing: 0.5px;
}

/* Sections */
.section { margin: 35px 0; }
.section h2 {
  font-size: 1.4em; margin-bottom: 14px; padding-bottom: 8px;
  border-bottom: 3px solid var(--accent); display: inline-block;
}

/* Cards */
.card {
  background: var(--card-bg); border-radius: 8px;
  box-shadow: var(--card-shadow); padding: 18px; margin-bottom: 14px;
}

/* Stats grid */
.stats-grid {
  display: grid; grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
  gap: 12px; margin-bottom: 20px;
}
.stat-box {
  background: var(--card-bg); border-radius: 8px; padding: 14px;
  box-shadow: var(--card-shadow); text-align: center;
}
.stat-box .value { font-size: 1.8em; font-weight: 700; color: var(--accent); }
.stat-box .label { font-size: 0.85em; color: var(--text-dim); }

/* Severity breakdown */
.sev-row { display: flex; gap: 10px; justify-content: center; flex-wrap: wrap; margin-bottom: 18px; }
.sev-box {
  padding: 8px 22px; border-radius: 6px; color: #fff;
  font-weight: 700; text-align: center; min-width: 100px;
}
.sev-box .count { font-size: 1.6em; display: block; }

/* Tables */
table { width: 100%; border-collapse: collapse; font-size: 0.9em; margin-top: 10px; }
th {
  background: #333; color: #fff; padding: 8px 10px; text-align: left;
  cursor: pointer; user-select: none; position: sticky; top: 0;
}
th:hover { background: #444; }
td { padding: 7px 10px; border-bottom: 1px solid var(--border); }
tr:hover { background: var(--bg2); }
.sev-badge {
  display: inline-block; padding: 2px 10px; border-radius: 4px;
  color: #fff; font-weight: 600; font-size: 0.85em;
}

/* Charts */
.chart-row { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin: 18px 0; }
.chart-box { background: var(--card-bg); border-radius: 8px; padding: 16px; box-shadow: var(--card-shadow); }
.chart-box canvas { max-height: 280px; }
@media (max-width: 700px) { .chart-row { grid-template-columns: 1fr; } }

/* Details/summary (investigations) */
details { margin-bottom: 10px; }
summary {
  cursor: pointer; padding: 10px 14px; background: var(--card-bg);
  border-radius: 6px; font-weight: 600; box-shadow: var(--card-shadow);
}
summary:hover { background: var(--bg2); }
details[open] summary { border-radius: 6px 6px 0 0; }
.detail-body { padding: 14px; background: var(--card-bg); border-radius: 0 0 6px 6px; border-top: 2px solid var(--accent); }
.detail-field { margin: 3px 0; }
.detail-field strong { display: inline-block; min-width: 140px; font-size: 0.9em; }

/* Recommended actions */
.action-item { display: flex; gap: 12px; align-items: flex-start; margin-bottom: 12px; }
.action-badge {
  padding: 4px 12px; border-radius: 4px; color: #fff;
  font-weight: 700; font-size: 0.8em; white-space: nowrap; min-width: 75px; text-align: center;
}
.action-text h4 { margin-bottom: 2px; font-size: 0.95em; }
.action-text p { color: var(--text-dim); font-size: 0.85em; }
</style>"""

    # ==================================================================
    # Cover
    # ==================================================================

    def _cover_section(self, now, alerts, profiles, duration, connections, overall_risk, risk_color):
        dur_str = ""
        if duration:
            mins = int(duration // 60)
            secs = int(duration % 60)
            dur_str = f"<span>Duration: {mins}m {secs}s</span> &bull; "

        return f"""
<div class="cover">
  <h1>NetWatch</h1>
  <p class="subtitle">Network Security Assessment Report</p>
  <div class="accent-line"></div>
  <p class="meta">
    Generated: {_esc(now.strftime('%Y-%m-%d %H:%M:%S'))} &bull;
    Version: {_esc(self._version)} &bull;
    {dur_str}
    Alerts: {len(alerts)} &bull;
    Processes: {len(profiles)} &bull;
    Connections: {connections}
  </p>
  <div class="risk-badge" style="background:{risk_color}">
    Overall Risk: {overall_risk.value}
  </div>
</div>
"""

    # ==================================================================
    # Executive Summary
    # ==================================================================

    def _executive_summary(self, sev_counts, alerts, profiles, duration, connections):
        risky = [p for p in profiles if p.risk_score >= 30]
        total = len(alerts)

        summary = (
            f"NetWatch recorded {connections} network connections"
            + (f" over {int((duration or 0) // 60)}m {int((duration or 0) % 60)}s" if duration else "")
            + f", profiling {len(profiles)} unique processes. "
        )
        if total:
            summary += (
                f"A total of {total} alert(s) were raised: "
                f"{sev_counts[Severity.CRITICAL]} critical, "
                f"{sev_counts[Severity.HIGH]} high, "
                f"{sev_counts[Severity.MEDIUM]} medium, "
                f"{sev_counts[Severity.LOW]} low."
            )
        else:
            summary += "No alerts were raised during the scan."

        if risky:
            summary += (
                f" {len(risky)} process(es) scored 30 or above on the risk scale "
                "and warrant further review."
            )

        return f"""
<div class="section">
  <h2>Executive Summary</h2>
  <div class="sev-row">
    <div class="sev-box" style="background:var(--sev-critical)"><span class="count">{sev_counts[Severity.CRITICAL]}</span>CRITICAL</div>
    <div class="sev-box" style="background:var(--sev-high)"><span class="count">{sev_counts[Severity.HIGH]}</span>HIGH</div>
    <div class="sev-box" style="background:var(--sev-medium)"><span class="count">{sev_counts[Severity.MEDIUM]}</span>MEDIUM</div>
    <div class="sev-box" style="background:var(--sev-low)"><span class="count">{sev_counts[Severity.LOW]}</span>LOW</div>
  </div>
  <p>{_esc(summary)}</p>
  <div class="chart-row">
    <div class="chart-box"><canvas id="sevChart"></canvas></div>
    <div class="chart-box"><canvas id="protoChart"></canvas></div>
  </div>
</div>
"""

    # ==================================================================
    # Network Statistics
    # ==================================================================

    def _network_stats_section(self, stats: dict) -> str:
        stat_items = [
            ("Total Connections", stats.get("total_connections", 0)),
            ("Unique Remote IPs", stats.get("unique_remote_ips", 0)),
            ("Unique Remote Ports", stats.get("unique_remote_ports", 0)),
            ("Unique Processes", stats.get("unique_processes", 0)),
            ("TCP", stats.get("tcp_count", 0)),
            ("UDP", stats.get("udp_count", 0)),
            ("Established", stats.get("established_count", 0)),
            ("Listening", stats.get("listen_count", 0)),
            ("Internal", stats.get("internal_count", 0)),
            ("External", stats.get("external_count", 0)),
        ]

        boxes = "\n".join(
            f'<div class="stat-box"><div class="value">{v}</div><div class="label">{_esc(l)}</div></div>'
            for l, v in stat_items
        )

        # Top IPs table
        top_ips_html = ""
        top_ips = stats.get("top_remote_ips", [])
        if top_ips:
            rows = "\n".join(
                f"<tr><td>{_esc(ip)}</td><td>{count}</td></tr>"
                for ip, count in top_ips[:10]
            )
            top_ips_html = f"""
<h3>Top Remote IPs</h3>
<table><tr><th>IP Address</th><th>Connections</th></tr>{rows}</table>
"""

        # Top Processes table
        top_procs_html = ""
        top_procs = stats.get("top_processes", [])
        if top_procs:
            rows = "\n".join(
                f"<tr><td>{_esc(name)}</td><td>{pid}</td><td>{count}</td></tr>"
                for name, pid, count in top_procs[:10]
            )
            top_procs_html = f"""
<h3>Top Processes</h3>
<table><tr><th>Process</th><th>PID</th><th>Connections</th></tr>{rows}</table>
"""

        # Top Ports table
        top_ports_html = ""
        top_ports = stats.get("top_remote_ports", [])
        if top_ports:
            rows = "\n".join(
                f"<tr><td>{port}</td><td>{count}</td></tr>"
                for port, count in top_ports[:10]
            )
            top_ports_html = f"""
<h3>Top Remote Ports</h3>
<table><tr><th>Port</th><th>Connections</th></tr>{rows}</table>
"""

        return f"""
<div class="section">
  <h2>Network Statistics</h2>
  <div class="stats-grid">{boxes}</div>
  <div class="chart-row">
    <div class="chart-box"><canvas id="dirChart"></canvas></div>
    <div class="chart-box"><canvas id="topIpChart"></canvas></div>
  </div>
  {top_ips_html}
  {top_procs_html}
  {top_ports_html}
</div>
"""

    # ==================================================================
    # Network Map
    # ==================================================================

    @staticmethod
    def _network_map_section(network_map_path: str) -> str:
        return f"""
<div class="section">
  <h2>Network Map</h2>
  <div class="card">
    <p>Process-to-endpoint graph generated alongside this report:</p>
    <p><a href="{_esc(network_map_path)}">{_esc(network_map_path)}</a></p>
  </div>
</div>
"""

    # ==================================================================
    # Scheduled Task Findings
    # ==================================================================

    def _task_findings_section(self, findings: list) -> str:
        rows = []
        for finding in findings:
            color = _COLOURS.get(finding.severity, "#95a5a6")
            reasons = "; ".join(finding.reasons)
            rows.append(
                f"<tr>"
                f"<td><span class='sev-badge' style='background:{color}'>{finding.severity.value}</span></td>"
                f"<td>{_esc(finding.task_name)}</td>"
                f"<td>{_esc(finding.status)}</td>"
                f"<td>{_esc(finding.command)}</td>"
                f"<td>{_esc(reasons)}</td>"
                f"</tr>"
            )

        return f"""
<div class="section">
  <h2>Scheduled Task Findings ({len(findings)})</h2>
  <table>
    <tr><th>Severity</th><th>Task</th><th>Status</th><th>Command</th><th>Reasons</th></tr>
    {"".join(rows)}
  </table>
</div>
"""

    # ==================================================================
    # Response Actions
    # ==================================================================

    def _response_results_section(self, results: list) -> str:
        rows = []
        for result in results:
            status = "OK" if result.success else "SKIP/FAIL"
            destination = result.destination or ""
            rows.append(
                f"<tr>"
                f"<td>{_esc(status)}</td>"
                f"<td>{_esc(result.action)}</td>"
                f"<td>{result.pid}</td>"
                f"<td>{_esc(result.process_name)}</td>"
                f"<td>{_esc(result.message)}</td>"
                f"<td>{_esc(destination)}</td>"
                f"</tr>"
            )

        return f"""
<div class="section">
  <h2>Response Actions ({len(results)})</h2>
  <table>
    <tr><th>Status</th><th>Action</th><th>PID</th><th>Process</th><th>Message</th><th>Destination</th></tr>
    {"".join(rows)}
  </table>
</div>
"""

    # ==================================================================
    # Alerts Table
    # ==================================================================

    def _alerts_section(self, alerts: list[Alert]) -> str:
        rows = []
        for a in alerts:
            color = _COLOURS.get(a.severity, "#95a5a6")
            ts = datetime.fromtimestamp(a.timestamp).strftime("%H:%M:%S")
            remote = ""
            if a.details.get("remote_addr"):
                remote = f"{a.details['remote_addr']}:{a.details.get('remote_port', '')}"
            rows.append(
                f"<tr>"
                f"<td><span class='sev-badge' style='background:{color}'>{a.severity.value}</span></td>"
                f"<td>{_esc(ts)}</td>"
                f"<td>{_esc(a.rule_name)}</td>"
                f"<td>{a.pid}</td>"
                f"<td>{_esc(a.process_name)}</td>"
                f"<td>{_esc(a.description)}</td>"
                f"<td>{_esc(remote)}</td>"
                f"</tr>"
            )

        return f"""
<div class="section">
  <h2>Alerts ({len(alerts)})</h2>
  <table id="alertsTable">
    <thead>
      <tr>
        <th onclick="sortTable('alertsTable',0)">Severity</th>
        <th onclick="sortTable('alertsTable',1)">Time</th>
        <th onclick="sortTable('alertsTable',2)">Rule</th>
        <th onclick="sortTable('alertsTable',3)">PID</th>
        <th onclick="sortTable('alertsTable',4)">Process</th>
        <th onclick="sortTable('alertsTable',5)">Description</th>
        <th onclick="sortTable('alertsTable',6)">Remote</th>
      </tr>
    </thead>
    <tbody>
      {"".join(rows)}
    </tbody>
  </table>
</div>
"""

    # ==================================================================
    # Process Risk Scores
    # ==================================================================

    def _process_section(self, profiles: list[ProcessProfile]) -> str:
        sorted_profiles = sorted(profiles, key=lambda p: p.risk_score, reverse=True)
        rows = []
        for p in sorted_profiles[:50]:
            risk = p.risk_score
            if risk >= 50:
                color = _COLOURS[Severity.CRITICAL]
            elif risk >= 30:
                color = _COLOURS[Severity.HIGH]
            elif risk >= 15:
                color = _COLOURS[Severity.MEDIUM]
            else:
                color = _COLOURS[Severity.LOW]

            rows.append(
                f"<tr>"
                f"<td>{p.pid}</td>"
                f"<td>{_esc(p.name)}</td>"
                f"<td><span class='sev-badge' style='background:{color}'>{risk}</span></td>"
                f"<td>{len(p.alerts)}</td>"
                f"<td>{len(p.unique_remote_ips)}</td>"
                f"<td>{len(p.unique_remote_ports)}</td>"
                f"<td>{_esc(p.username or 'N/A')}</td>"
                f"</tr>"
            )

        return f"""
<div class="section">
  <h2>Process Risk Scores</h2>
  <table id="processTable">
    <thead>
      <tr>
        <th onclick="sortTable('processTable',0)">PID</th>
        <th onclick="sortTable('processTable',1)">Name</th>
        <th onclick="sortTable('processTable',2)">Risk</th>
        <th onclick="sortTable('processTable',3)">Alerts</th>
        <th onclick="sortTable('processTable',4)">IPs</th>
        <th onclick="sortTable('processTable',5)">Ports</th>
        <th onclick="sortTable('processTable',6)">User</th>
      </tr>
    </thead>
    <tbody>
      {"".join(rows)}
    </tbody>
  </table>
</div>
"""

    # ==================================================================
    # Investigations (collapsible)
    # ==================================================================

    def _investigation_section(self, investigations: list) -> str:
        items = []
        for inv in investigations:
            fields_html = ""
            fields = [
                ("Executable", inv.exe_path),
                ("Exists on disk", inv.exe_exists_on_disk),
                ("Signature", getattr(inv, "exe_signed", None)),
                ("Command line", inv.cmdline),
                ("User", inv.username),
                ("Working dir", inv.cwd),
                ("Status", inv.status),
                ("Parent", f"PID {inv.parent_pid} ({inv.parent_name})" if inv.parent_pid else None),
                ("Threads", inv.num_threads),
                ("Memory", f"{inv.memory_mb:.1f} MB" if inv.memory_mb else None),
                ("CPU %", f"{inv.cpu_percent:.1f}%" if inv.cpu_percent is not None else None),
            ]
            for label, value in fields:
                if value is not None:
                    fields_html += f'<div class="detail-field"><strong>{_esc(label)}:</strong> {_esc(str(value))}</div>\n'

            # Connections
            if inv.connections:
                fields_html += f'<div class="detail-field"><strong>Connections ({len(inv.connections)}):</strong></div>\n'
                for c in inv.connections[:8]:
                    fields_html += f'<div class="detail-field" style="padding-left:20px">{_esc(c["local"])} &rarr; {_esc(c["remote"])} [{_esc(c["status"])}]</div>\n'
                if len(inv.connections) > 8:
                    fields_html += f'<div class="detail-field" style="padding-left:20px;color:var(--text-dim)">... and {len(inv.connections) - 8} more</div>\n'

            # Suspicious DLLs
            if inv.suspicious_dlls:
                fields_html += f'<div class="detail-field" style="color:var(--sev-high);font-weight:bold">\u26a0 Suspicious DLLs ({len(inv.suspicious_dlls)}):</div>\n'
                for dll in inv.suspicious_dlls[:10]:
                    fields_html += f'<div class="detail-field" style="padding-left:20px"><strong>{_esc(dll["name"])}</strong> — {_esc(dll["path"])}</div>\n'
                    for reason in dll.get("reasons", []):
                        fields_html += f'<div class="detail-field" style="padding-left:40px;color:var(--sev-medium)">&rarr; {_esc(reason)}</div>\n'

            if inv.exe_exists_on_disk is False:
                fields_html += '<div class="detail-field" style="color:var(--sev-critical);font-weight:bold">\u26a0 EXECUTABLE NOT FOUND ON DISK — possible fileless malware</div>\n'

            items.append(f"""
<details>
  <summary>PID {inv.pid} — {_esc(inv.name)}</summary>
  <div class="detail-body">{fields_html}</div>
</details>
""")

        return f"""
<div class="section">
  <h2>Process Investigations</h2>
  {"".join(items)}
</div>
"""

    # ==================================================================
    # DLL Scan Results
    # ==================================================================

    def _dll_section(self, dll_results: list) -> str:
        total_findings = sum(len(r.suspicious_modules) for r in dll_results)
        items = []
        for r in dll_results:
            if not r.suspicious_modules:
                continue
            dlls_html = ""
            for dll in r.suspicious_modules:
                disk_tag = ' <span style="color:var(--sev-critical);font-weight:bold">[MISSING FROM DISK]</span>' \
                    if not dll.get("exists_on_disk", True) else ""
                dlls_html += f'<div style="margin:6px 0"><strong>{_esc(dll["name"])}</strong>{disk_tag}<br>'
                dlls_html += f'<span style="color:var(--text-dim)">{_esc(dll["path"])}</span><br>'
                for reason in dll.get("reasons", []):
                    dlls_html += f'<span style="color:var(--sev-medium)">&rarr; {_esc(reason)}</span><br>'
                dlls_html += "</div>"

            items.append(f"""
<details>
  <summary>PID {r.pid} — {_esc(r.process_name)} ({len(r.suspicious_modules)} suspicious / {r.total_modules} total)</summary>
  <div class="detail-body">{dlls_html}</div>
</details>
""")

        return f"""
<div class="section">
  <h2>DLL Injection Scan ({total_findings} finding(s))</h2>
  {"".join(items)}
</div>
"""

    # ==================================================================
    # Feed Status
    # ==================================================================

    def _feed_section(self, feed_status: dict) -> str:
        rows = []
        for name, status in feed_status.items():
            updated = status.last_updated.strftime("%Y-%m-%d %H:%M") if status.last_updated else "never"
            rows.append(
                f"<tr>"
                f"<td>{_esc(name)}</td>"
                f"<td>{_esc(status.description)}</td>"
                f"<td>{_esc(updated)}</td>"
                f"<td>{status.entry_count}</td>"
                f"</tr>"
            )

        return f"""
<div class="section">
  <h2>Threat Intelligence Feeds</h2>
  <table>
    <tr><th>Feed</th><th>Description</th><th>Last Updated</th><th>Entries</th></tr>
    {"".join(rows)}
  </table>
</div>
"""

    # ==================================================================
    # Recommended Actions
    # ==================================================================

    def _recommended_actions(self, alerts, profiles, dll_results) -> str:
        actions = self._build_actions(alerts, profiles, dll_results)

        items = []
        for priority, action, rationale in actions:
            color = {
                "CRITICAL": _COLOURS[Severity.CRITICAL],
                "HIGH": _COLOURS[Severity.HIGH],
                "MEDIUM": _COLOURS[Severity.MEDIUM],
                "LOW": _COLOURS[Severity.LOW],
            }.get(priority, "#333")

            items.append(f"""
<div class="action-item">
  <span class="action-badge" style="background:{color}">{_esc(priority)}</span>
  <div class="action-text">
    <h4>{_esc(action)}</h4>
    <p>{_esc(rationale)}</p>
  </div>
</div>
""")

        return f"""
<div class="section">
  <h2>Recommended Actions</h2>
  <p style="color:var(--text-dim);margin-bottom:14px">
    Actions are listed in order of priority based on the findings in this report.
  </p>
  {"".join(items)}
</div>
"""

    @staticmethod
    def _build_actions(alerts, profiles, dll_results):
        actions = []
        sev_counts = {s: 0 for s in Severity}
        for a in alerts:
            sev_counts[a.severity] += 1

        if sev_counts[Severity.CRITICAL]:
            actions.append((
                "CRITICAL",
                "Isolate affected hosts and investigate critical alerts immediately",
                f"{sev_counts[Severity.CRITICAL]} critical alert(s) detected — "
                "these may indicate active compromise or C2 communication.",
            ))
        if sev_counts[Severity.HIGH]:
            actions.append((
                "HIGH",
                "Review and triage high-severity alerts within 24 hours",
                f"{sev_counts[Severity.HIGH]} high-severity alert(s) require "
                "prompt analysis to rule out malicious activity.",
            ))

        c2_alerts = [a for a in alerts if "c2" in a.rule_name.lower() or "threat" in a.rule_name.lower()]
        if c2_alerts:
            actions.append((
                "CRITICAL",
                "Block identified C2 IP addresses at the firewall",
                f"{len(c2_alerts)} connection(s) matched known command-and-control indicators.",
            ))

        lateral_alerts = [a for a in alerts if "lateral" in a.rule_name.lower()]
        if lateral_alerts:
            actions.append((
                "HIGH",
                "Investigate lateral movement activity between internal hosts",
                f"{len(lateral_alerts)} lateral movement indicator(s) detected. "
                "Check for unauthorised remote access or automated reconnaissance.",
            ))

        risky = [p for p in profiles if p.risk_score >= 30]
        if risky:
            names = ", ".join(dict.fromkeys(p.name for p in risky[:5]))
            actions.append((
                "HIGH",
                f"Investigate high-risk processes: {names}",
                f"{len(risky)} process(es) scored >= 30 on the risk scale.",
            ))

        if dll_results:
            suspicious_count = sum(len(entry.suspicious_modules) for entry in dll_results)
            if suspicious_count:
                actions.append((
                    "HIGH",
                    "Investigate suspicious DLL modules flagged by the inspector",
                    f"{suspicious_count} DLL(s) matched injection or side-loading indicators.",
                ))

        actions.append((
            "LOW",
            "Schedule regular NetWatch scans to establish a network baseline",
            "Periodic monitoring helps distinguish normal traffic from anomalies.",
        ))

        return actions

    # ==================================================================
    # Chart.js scripts
    # ==================================================================

    def _build_chart_data(self, sev_counts, network_stats) -> dict:
        data = {
            "sev_labels": ["CRITICAL", "HIGH", "MEDIUM", "LOW"],
            "sev_values": [
                sev_counts[Severity.CRITICAL], sev_counts[Severity.HIGH],
                sev_counts[Severity.MEDIUM], sev_counts[Severity.LOW],
            ],
            "sev_colors": [
                _COLOURS[Severity.CRITICAL], _COLOURS[Severity.HIGH],
                _COLOURS[Severity.MEDIUM], _COLOURS[Severity.LOW],
            ],
        }

        if network_stats:
            data["proto_labels"] = ["TCP", "UDP"]
            data["proto_values"] = [
                network_stats.get("tcp_count", 0),
                network_stats.get("udp_count", 0),
            ]
            data["dir_labels"] = ["Internal", "External"]
            data["dir_values"] = [
                network_stats.get("internal_count", 0),
                network_stats.get("external_count", 0),
            ]
            top_ips = network_stats.get("top_remote_ips", [])[:8]
            data["top_ip_labels"] = [ip for ip, _ in top_ips]
            data["top_ip_values"] = [count for _, count in top_ips]

        return data

    @staticmethod
    def _chart_scripts(data: dict) -> str:
        import json
        return f"""
<script>
const chartData = {json.dumps(data)};

// Severity donut
if (document.getElementById('sevChart')) {{
  new Chart(document.getElementById('sevChart'), {{
    type: 'doughnut',
    data: {{
      labels: chartData.sev_labels,
      datasets: [{{
        data: chartData.sev_values,
        backgroundColor: chartData.sev_colors,
        borderWidth: 2,
      }}]
    }},
    options: {{
      responsive: true,
      plugins: {{
        legend: {{ position: 'bottom' }},
        title: {{ display: true, text: 'Alert Severity Distribution' }}
      }}
    }}
  }});
}}

// Protocol pie
if (document.getElementById('protoChart') && chartData.proto_values) {{
  new Chart(document.getElementById('protoChart'), {{
    type: 'pie',
    data: {{
      labels: chartData.proto_labels,
      datasets: [{{
        data: chartData.proto_values,
        backgroundColor: ['#2ecc71', '#f39c12'],
        borderWidth: 2,
      }}]
    }},
    options: {{
      responsive: true,
      plugins: {{
        legend: {{ position: 'bottom' }},
        title: {{ display: true, text: 'Protocol Breakdown' }}
      }}
    }}
  }});
}}

// Traffic direction bar
if (document.getElementById('dirChart') && chartData.dir_values) {{
  new Chart(document.getElementById('dirChart'), {{
    type: 'bar',
    data: {{
      labels: chartData.dir_labels,
      datasets: [{{
        data: chartData.dir_values,
        backgroundColor: ['#2ecc71', '#e74c3c'],
        borderRadius: 6,
      }}]
    }},
    options: {{
      responsive: true,
      plugins: {{
        legend: {{ display: false }},
        title: {{ display: true, text: 'Traffic Direction' }}
      }},
      scales: {{ y: {{ beginAtZero: true }} }}
    }}
  }});
}}

// Top IPs horizontal bar
if (document.getElementById('topIpChart') && chartData.top_ip_labels) {{
  new Chart(document.getElementById('topIpChart'), {{
    type: 'bar',
    data: {{
      labels: chartData.top_ip_labels,
      datasets: [{{
        data: chartData.top_ip_values,
        backgroundColor: '#3498db',
        borderRadius: 4,
      }}]
    }},
    options: {{
      indexAxis: 'y',
      responsive: true,
      plugins: {{
        legend: {{ display: false }},
        title: {{ display: true, text: 'Top Remote IPs' }}
      }},
      scales: {{ x: {{ beginAtZero: true }} }}
    }}
  }});
}}

// Sortable table
function sortTable(tableId, colIdx) {{
  const table = document.getElementById(tableId);
  const tbody = table.querySelector('tbody');
  const rows = Array.from(tbody.querySelectorAll('tr'));
  const dir = table.dataset.sortDir === 'asc' ? 'desc' : 'asc';
  table.dataset.sortDir = dir;
  rows.sort((a, b) => {{
    let aText = a.cells[colIdx].textContent.trim();
    let bText = b.cells[colIdx].textContent.trim();
    let aNum = parseFloat(aText), bNum = parseFloat(bText);
    if (!isNaN(aNum) && !isNaN(bNum)) {{
      return dir === 'asc' ? aNum - bNum : bNum - aNum;
    }}
    return dir === 'asc' ? aText.localeCompare(bText) : bText.localeCompare(aText);
  }});
  rows.forEach(row => tbody.appendChild(row));
}}
</script>
"""

    # ==================================================================
    # Helpers
    # ==================================================================

    @staticmethod
    def _overall_risk(alerts: list[Alert]) -> Severity:
        if not alerts:
            return Severity.LOW
        if any(a.severity == Severity.CRITICAL for a in alerts):
            return Severity.CRITICAL
        if any(a.severity == Severity.HIGH for a in alerts):
            return Severity.HIGH
        if any(a.severity == Severity.MEDIUM for a in alerts):
            return Severity.MEDIUM
        return Severity.LOW
