"""
Learning mode helpers for generating environment-specific whitelist entries.

The learner is intentionally conservative: it only suggests LOW/MEDIUM
suppression rules, and connection-specific rules include the observed endpoint
details instead of suppressing every alert for a process.
"""

from __future__ import annotations

import json
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

from .models import Alert, Severity


BROAD_LEARNABLE_RULES = {
    "External Listener",
    "Non-standard DNS Port",
    "DNS Exfiltration Suspect",
}

DETAIL_LEARNABLE_RULES = {
    "External High-Port Connection",
}

LEARNABLE_SEVERITIES = {Severity.LOW, Severity.MEDIUM}


class LearningWhitelistBuilder:
    """Builds whitelist suggestions from alerts observed during learning mode."""

    def build(self, alerts: list[Alert], min_occurrences: int = 1) -> dict[str, Any]:
        """Return a whitelist JSON object from learnable alerts."""
        min_occurrences = max(1, min_occurrences)
        broad_counts: Counter[tuple[str, str]] = Counter()
        detail_counts: Counter[tuple[str, tuple[tuple[str, Any], ...]]] = Counter()

        for alert in alerts:
            if alert.severity not in LEARNABLE_SEVERITIES:
                continue

            proc = alert.process_name
            if alert.rule_name in BROAD_LEARNABLE_RULES:
                broad_counts[(proc, alert.rule_name)] += 1
            elif alert.rule_name in DETAIL_LEARNABLE_RULES:
                entry = self._connection_entry(alert)
                if entry:
                    detail_counts[(proc, tuple(sorted(entry.items())))] += 1

        learned: dict[str, Any] = {
            "_comment": (
                "Generated by NetWatch learning mode. Review before using in "
                "production, especially broad process-level suppressions."
            ),
            "_generated_at": datetime.now(timezone.utc).isoformat(),
        }

        processes = sorted({p for p, _ in broad_counts} | {p for p, _ in detail_counts})
        for proc in processes:
            entries: list[Any] = []
            for (entry_proc, rule_name), count in sorted(broad_counts.items()):
                if entry_proc == proc and count >= min_occurrences:
                    entries.append(rule_name)
            for (entry_proc, entry_items), count in sorted(detail_counts.items()):
                if entry_proc == proc and count >= min_occurrences:
                    entries.append(dict(entry_items))
            if entries:
                learned[proc] = entries

        return learned

    def write(
        self,
        alerts: list[Alert],
        path: str,
        *,
        min_occurrences: int = 1,
        merge_existing: bool = True,
    ) -> str:
        """Write learned whitelist entries and return the absolute path."""
        target = Path(path)
        learned = self.build(alerts, min_occurrences=min_occurrences)
        output = learned

        if merge_existing and target.is_file():
            try:
                existing = json.loads(target.read_text(encoding="utf-8"))
                if isinstance(existing, dict):
                    output = self.merge(existing, learned)
            except json.JSONDecodeError:
                output = learned

        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(json.dumps(output, indent=4, sort_keys=True), encoding="utf-8")
        return str(target.resolve())

    @staticmethod
    def count_entries(whitelist_data: dict[str, Any]) -> int:
        """Count non-metadata whitelist entries."""
        return sum(1 for key in whitelist_data if not key.startswith("_"))

    @staticmethod
    def merge(existing: dict[str, Any], learned: dict[str, Any]) -> dict[str, Any]:
        """Merge learned entries into an existing whitelist object."""
        merged = dict(existing)
        merged.setdefault("_comment", learned.get("_comment", "NetWatch whitelist"))
        merged["_learned_at"] = learned.get("_generated_at")

        for proc, learned_rules in learned.items():
            if proc.startswith("_"):
                continue
            current = merged.get(proc, [])
            if isinstance(current, str):
                current_rules: list[Any] = [current]
            elif isinstance(current, list):
                current_rules = list(current)
            elif current == "*" or current is True:
                current_rules = ["*"]
            else:
                current_rules = []

            for rule in learned_rules:
                if not any(LearningWhitelistBuilder._same_rule(rule, item) for item in current_rules):
                    current_rules.append(rule)
            merged[proc] = current_rules

        return merged

    @staticmethod
    def _connection_entry(alert: Alert) -> Optional[dict[str, Any]]:
        details = alert.details or {}
        remote_addr = details.get("remote_addr")
        remote_port = details.get("remote_port")
        if not remote_addr or not remote_port:
            return None
        return {
            "rule": alert.rule_name,
            "remote_addr": remote_addr,
            "remote_port": remote_port,
        }

    @staticmethod
    def _same_rule(left: Any, right: Any) -> bool:
        if isinstance(left, dict) and isinstance(right, dict):
            return left == right
        return left == right
